version: '3.8'
services:
  api:
    build: .
    container_name: kinchaku-api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - NODE_ENV=production
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
    restart: unless-stopped
