version: "3.8"
services:
  api:
    build: .
    container_name: kinchaku-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - DATABASE_PATH=/data/db.sqlite
      - NODE_ENV=production
    volumes:
      - ./data:/data
    restart: unless-stopped
